export const emojis = [
    {emoji: "⚽", name: "soccer ball"},
    {emoji: "🏀", name: "basketball"},
    {emoji: "🏈", name: "american football"},
    {emoji: "⚾", name: "baseball"},
    {emoji: "🎾", name: "tennis"},
    {emoji: "🏐", name: "volleyball"},
    {emoji: "🏉", name: "rugby football"},
    {emoji: "🎱", name: "pool 8 ball"},
    {emoji: "🏓", name: "ping pong"},
    {emoji: "🏸", name: "badminton"},
    {emoji: "🥊", name: "boxing glove"},
    {emoji: "🥋", name: "martial arts uniform"},
    {emoji: "🥅", name: "goal net"},
    {emoji: "⛳", name: "flag in hole (golf)"},
    {emoji: "🎣", name: "fishing pole"},
    {emoji: "🎽", name: "running shirt"},
    {emoji: "🎿", name: "ski"},
    {emoji: "🛷", name: "sled"},
    {emoji: "🏂", name: "snowboarder"},
    {emoji: "🏋️‍♂️", name: "man lifting weights"},
    {emoji: "🏋️‍♀️", name: "woman lifting weights"},
    {emoji: "🚴‍♂️", name: "man biking"},
    {emoji: "🚴‍♀️", name: "woman biking"},
    {emoji: "🚵‍♂️", name: "man mountain biking"},
    {emoji: "🚵‍♀️", name: "woman mountain biking"},
    {emoji: "🤸‍♂️", name: "man cartwheeling"},
    {emoji: "🤸‍♀️", name: "woman cartwheeling"},
    {emoji: "🧘‍♂️", name: "man in lotus position"},
    {emoji: "🧘‍♀️", name: "woman in lotus position"},
    {emoji: "🏇", name: "horse racing"},
    {emoji: "🧗‍♂️", name: "man climbing"},
    {emoji: "🧗‍♀️", name: "woman climbing"},
    {emoji: "🏊‍♂️", name: "man swimming"},
    {emoji: "🏊‍♀️", name: "woman swimming"},
    {emoji: "🤽‍♂️", name: "man playing water polo"},
    {emoji: "🤽‍♀️", name: "woman playing water polo"},
    {emoji: "🚣‍♂️", name: "man rowing boat"},
    {emoji: "🚣‍♀️", name: "woman rowing boat"},
    {emoji: "🧩", name: "puzzle piece (representing mental sports and activities)"},
    {emoji: "🎮", name: "video game"},
    {emoji: "🕹️", name: "joystick"},
    {emoji: "🛼", name: "roller skate"},
    {emoji: "🛹", name: "skateboard"},
    {emoji: "🪂", name: "parachute"},
    {emoji: "🏌️‍♂️", name: "man golfing"},
    {emoji: "🏌️‍♀️", name: "woman golfing"},
    {emoji: "🤹‍♂️", name: "man juggling"},
    {emoji: "🤹‍♀️", name: "woman juggling"},
    {emoji: "🎨", name: "artist palette (representing arts as an activity)"},
    {emoji: "🎭", name: "performing arts"},
    {emoji: "🎤", name: "microphone (representing singing or public speaking)"},
    {emoji: "🎯", name: "direct hit"},
    {emoji: "🪁", name: "kite"},
    {emoji: "🏹", name: "bow and arrow (archery)"},
    {emoji: "🥌", name: "curling stone"},
];
  